apiVersion: v1
kind: Pod # case-sensitive
metadata:
  name: nginx
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
    # - name: busybox-container
    #   image: busybox:latest
    #   command: ["sleep", "3600"]